
let mapleader = "\<Space>"

" Vundle set up
set nocompatible " be iMproved, required
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-fugitive'
Plugin 'thoughtbot/vim-rspec'
Plugin 'jiangmiao/auto-pairs'
Plugin 'Yggdroot/indentLine'
Plugin 'ervandew/supertab'

let g:rspec_command = "Dispatch rspec -I . --color -f p {spec}"

" CtrlP is a fuzzy file finder that allows you to very rapidly find a file without needing to type out (or even know) the full path to the file.
Plugin 'ctrlpvim/ctrlp.vim'

" Make CtrlP use ag for listing the files. Way faster and no useless files.
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

Plugin 'altercation/vim-colors-solarized'
Plugin 'vim-ruby/vim-ruby'
Plugin 'MarcWeber/vim-addon-mw-utils' " Needed for vim-snipmate
Plugin 'tomtom/tlib_vim' " Needed for vim-snipmate
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin '907th/vim-auto-save'
let g:auto_save = 1
Plugin 'slim-template/vim-slim.git'
Plugin 'kchmck/vim-coffee-script'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_symbols.crypt = '🔒'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.maxlinenr = '☰'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.spell = 'Ꞩ'
let g:airline_symbols.notexists = '∄'
let g:airline_symbols.whitespace = 'Ξ'

Plugin 'scrooloose/nerdtree'
let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeAutoDeleteBuffer = 1
let NERDTreeIgnore=['.git$', '\.swp$', '\.DS_Store$']
Plugin 'jeffkreeftmeijer/vim-numbertoggle'
Plugin 'djoshea/vim-autoread'

" JS plugins for VIM
Plugin 'mxw/vim-jsx'
let g:jsx_ext_required = 0
Plugin 'pangloss/vim-javascript'
Plugin 'elzr/vim-json'
let g:indentLine_noConcealCursor="" " Needed because of Yggdroot/indentLine
Plugin 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exec = 'eslint_d' " Faster syntax checking
let g:syntastic_json_checkers=['jsonlint']
let g:syntastic_error_symbol = '❌'
let g:syntastic_style_error_symbol = '⁉️'
let g:syntastic_warning_symbol = '⚠️'
let g:syntastic_style_warning_symbol = '💩'
" npm install -g eslint eslint-config-standard eslint-plugin-import eslint-plugin-promise eslint-plugin-react eslint-plugin-standard
" Plugin 'alvan/vim-closetag'
" let g:closetag_filenames = "*.html,*.xhtml,*.phtml,*.js"
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set t_Co=256
syntax enable
set background=light
colorscheme solarized

" Vim mappings and settings

" nmap means nomal mode mapping, in nomal mode, map ^ to 0 to easy access to the start of the line
nmap 0 ^

" ve means vim edit
nmap <leader>ve :vsplit $MYVIMRC<cr>

" vr means vim reload
nmap <leader>vr :source $MYVIMRC<cr>

" opens NerdTree
nmap <leader>n :NERDTreeToggle<CR>

" Shift-Enter to escape in Insert Mode
inoremap ✠ <Esc>

" Navigation around windows
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>

set encoding=utf-8
set number
set wildmenu
set wildmode=full
set switchbuf=useopen,usetab
set history=500
set splitbelow
set splitright
set numberwidth=4
set nowrap
set showcmd
set backspace=indent,eol,start
set tabstop=2
set shiftwidth=2
set expandtab
set hlsearch
set incsearch
set ignorecase
set cursorline
set laststatus=2
set formatoptions-=or " Don't add the comment prefix when I hit enter or o/O on a comment line."

" Lower timeout for mappings (faster response)
set ttimeout
set timeout timeoutlen=300 ttimeoutlen=300

set noswapfile " No stupid .swp file
set clipboard=unnamed " Yanks text into system clipboard
set pastetoggle=<leader>p " Toggle paste and nopaste mode

" Make VIM run fast even in large long lines files
set synmaxcol=300

nmap <Leader><CR> :nohlsearch<cr>

" RSpec.vim mappings

map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

inoremap jk <C-o>a
inoremap kj <C-o>A
inoremap ;; <C-o>a;<C-o>h
inoremap ,, <C-o>a,<CR><C-o>b<C-o>a

" Buffer switching
map <leader>b :e#<CR> " open last opened file

" Quickfix windows open and close
map <Leader>qq :cclose<CR>
map <Leader>qf :copen<CR>

